// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    id,
    name,
    active
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, active, created_at, updated_at
`

type CreateAssetParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset, arg.ID, arg.Name, arg.Active)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, name, active, created_at, updated_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, name, active, created_at, updated_at
FROM assets
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListAssets(ctx context.Context, limitCount int32) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssets = `-- name: SearchAssets :many
SELECT
    id,
    name,
    active,
    created_at,
    updated_at
FROM assets
WHERE name ILIKE $1::text ESCAPE '\'
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type SearchAssetsParams struct {
	SearchPattern string `json:"search_pattern"`
	LimitCount    int32  `json:"limit_count"`
}

func (q *Queries) SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssets, arg.SearchPattern, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
