// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    id,
    name,
    active
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, active, created_at, updated_at
`

type CreateAssetParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset, arg.ID, arg.Name, arg.Active)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAsset = `-- name: DeactivateAsset :one
WITH updated AS (
    UPDATE assets
    SET
        active = false,
        updated_at = now()
    WHERE id = $1
      AND active = true
    RETURNING id
)
SELECT count(*)::int
FROM updated
`

func (q *Queries) DeactivateAsset(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, deactivateAsset, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findAssetByNameExcludingID = `-- name: FindAssetByNameExcludingID :one
SELECT
    id,
    name,
    active,
    created_at,
    updated_at
FROM assets
WHERE lower(name) = lower($1)
  AND id <> $2
LIMIT 1
`

type FindAssetByNameExcludingIDParams struct {
	Name       string `json:"name"`
	ExcludedID string `json:"excluded_id"`
}

func (q *Queries) FindAssetByNameExcludingID(ctx context.Context, arg FindAssetByNameExcludingIDParams) (Asset, error) {
	row := q.db.QueryRow(ctx, findAssetByNameExcludingID, arg.Name, arg.ExcludedID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, name, active, created_at, updated_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, name, active, created_at, updated_at
FROM assets
WHERE
    (
        $1::text = 'all'
        OR ($1::text = 'active' AND active = true)
        OR ($1::text = 'inactive' AND active = false)
    )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAssetsParams struct {
	StatusFilter string `json:"status_filter"`
	LimitCount   int32  `json:"limit_count"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, arg.StatusFilter, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateAsset = `-- name: ReactivateAsset :one
WITH updated AS (
    UPDATE assets
    SET
        active = true,
        updated_at = now()
    WHERE id = $1
      AND active = false
    RETURNING id
)
SELECT count(*)::int
FROM updated
`

func (q *Queries) ReactivateAsset(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, reactivateAsset, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const searchAssets = `-- name: SearchAssets :many
WITH search_terms AS (
    SELECT unnest($3::text[]) AS search_pattern
)
SELECT
    id,
    name,
    active,
    created_at,
    updated_at
FROM assets
WHERE
    (
        $1::text = 'all'
        OR ($1::text = 'active' AND active = true)
        OR ($1::text = 'inactive' AND active = false)
    )
    AND NOT EXISTS (
        SELECT 1
        FROM search_terms
        WHERE NOT (
            name ILIKE search_terms.search_pattern ESCAPE '\'
        )
    )
ORDER BY active DESC, created_at DESC, id DESC
LIMIT $2
`

type SearchAssetsParams struct {
	StatusFilter   string   `json:"status_filter"`
	LimitCount     int32    `json:"limit_count"`
	SearchPatterns []string `json:"search_patterns"`
}

func (q *Queries) SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssets, arg.StatusFilter, arg.LimitCount, arg.SearchPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :exec
UPDATE assets
SET
    name = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateAssetParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) error {
	_, err := q.db.Exec(ctx, updateAsset, arg.Name, arg.ID)
	return err
}
