// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    id,
    actor_operator_id,
    event_type,
    entity_type,
    entity_id,
    outcome,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateAuditEventParams struct {
	ID              string      `json:"id"`
	ActorOperatorID pgtype.Text `json:"actor_operator_id"`
	EventType       string      `json:"event_type"`
	EntityType      string      `json:"entity_type"`
	EntityID        string      `json:"entity_id"`
	Outcome         string      `json:"outcome"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorOperatorID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.Outcome,
		arg.Metadata,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
    ae.id,
    ae.actor_operator_id,
    COALESCE(o.alias, '') AS actor_alias,
    COALESCE(o.rank, '') AS actor_rank,
    ae.event_type,
    ae.entity_type,
    ae.entity_id,
    ae.outcome,
    ae.metadata,
    ae.occurred_at
FROM audit_events ae
LEFT JOIN operators o ON o.id = ae.actor_operator_id
ORDER BY ae.occurred_at DESC, ae.id DESC
LIMIT $1
`

type ListAuditEventsRow struct {
	ID              string             `json:"id"`
	ActorOperatorID pgtype.Text        `json:"actor_operator_id"`
	ActorAlias      string             `json:"actor_alias"`
	ActorRank       string             `json:"actor_rank"`
	EventType       string             `json:"event_type"`
	EntityType      string             `json:"entity_type"`
	EntityID        string             `json:"entity_id"`
	Outcome         string             `json:"outcome"`
	Metadata        []byte             `json:"metadata"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, limitCount int32) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorOperatorID,
			&i.ActorAlias,
			&i.ActorRank,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Outcome,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
