// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custody.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustodyLine = `-- name: CreateCustodyLine :one
INSERT INTO custody_lines (
    custody_transaction_id,
    asset_id,
    quantity
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, custody_transaction_id, asset_id, quantity, created_at
`

type CreateCustodyLineParams struct {
	CustodyTransactionID string `json:"custody_transaction_id"`
	AssetID              string `json:"asset_id"`
	Quantity             int32  `json:"quantity"`
}

func (q *Queries) CreateCustodyLine(ctx context.Context, arg CreateCustodyLineParams) (CustodyLine, error) {
	row := q.db.QueryRow(ctx, createCustodyLine, arg.CustodyTransactionID, arg.AssetID, arg.Quantity)
	var i CustodyLine
	err := row.Scan(
		&i.ID,
		&i.CustodyTransactionID,
		&i.AssetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createCustodyTransaction = `-- name: CreateCustodyTransaction :one
INSERT INTO custody_transactions (
    id,
    transaction_type,
    personnel_id,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, transaction_type, personnel_id, notes, created_at
`

type CreateCustodyTransactionParams struct {
	ID              string `json:"id"`
	TransactionType string `json:"transaction_type"`
	PersonnelID     string `json:"personnel_id"`
	Notes           string `json:"notes"`
}

func (q *Queries) CreateCustodyTransaction(ctx context.Context, arg CreateCustodyTransactionParams) (CustodyTransaction, error) {
	row := q.db.QueryRow(ctx, createCustodyTransaction,
		arg.ID,
		arg.TransactionType,
		arg.PersonnelID,
		arg.Notes,
	)
	var i CustodyTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionType,
		&i.PersonnelID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseCustodyBalanceForReturn = `-- name: DecreaseCustodyBalanceForReturn :execrows
UPDATE custody_balances
SET
    quantity = quantity - $1,
    updated_at = now()
WHERE personnel_id = $2
  AND asset_id = $3
  AND quantity >= $1
`

type DecreaseCustodyBalanceForReturnParams struct {
	Quantity    int32  `json:"quantity"`
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
}

func (q *Queries) DecreaseCustodyBalanceForReturn(ctx context.Context, arg DecreaseCustodyBalanceForReturnParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreaseCustodyBalanceForReturn, arg.Quantity, arg.PersonnelID, arg.AssetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustodyBalanceQuantity = `-- name: GetCustodyBalanceQuantity :one
SELECT quantity
FROM custody_balances
WHERE personnel_id = $1
  AND asset_id = $2
`

type GetCustodyBalanceQuantityParams struct {
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
}

func (q *Queries) GetCustodyBalanceQuantity(ctx context.Context, arg GetCustodyBalanceQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCustodyBalanceQuantity, arg.PersonnelID, arg.AssetID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const increaseCustodyBalanceForCheckout = `-- name: IncreaseCustodyBalanceForCheckout :exec
INSERT INTO custody_balances (
    personnel_id,
    asset_id,
    quantity
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (personnel_id, asset_id)
DO UPDATE SET
    quantity = custody_balances.quantity + EXCLUDED.quantity,
    updated_at = now()
`

type IncreaseCustodyBalanceForCheckoutParams struct {
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) IncreaseCustodyBalanceForCheckout(ctx context.Context, arg IncreaseCustodyBalanceForCheckoutParams) error {
	_, err := q.db.Exec(ctx, increaseCustodyBalanceForCheckout, arg.PersonnelID, arg.AssetID, arg.Quantity)
	return err
}

const listCurrentCustodyByPersonnel = `-- name: ListCurrentCustodyByPersonnel :many
SELECT
    cb.personnel_id,
    cb.asset_id,
    a.name AS asset_name,
    cb.quantity,
    cb.updated_at
FROM custody_balances cb
JOIN assets a ON a.id = cb.asset_id
WHERE cb.personnel_id = $1
  AND cb.quantity > 0
ORDER BY a.name ASC, cb.asset_id ASC
`

type ListCurrentCustodyByPersonnelRow struct {
	PersonnelID string             `json:"personnel_id"`
	AssetID     string             `json:"asset_id"`
	AssetName   string             `json:"asset_name"`
	Quantity    int32              `json:"quantity"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentCustodyByPersonnel(ctx context.Context, personnelID string) ([]ListCurrentCustodyByPersonnelRow, error) {
	rows, err := q.db.Query(ctx, listCurrentCustodyByPersonnel, personnelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentCustodyByPersonnelRow{}
	for rows.Next() {
		var i ListCurrentCustodyByPersonnelRow
		if err := rows.Scan(
			&i.PersonnelID,
			&i.AssetID,
			&i.AssetName,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
