// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custody.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustodyLine = `-- name: CreateCustodyLine :one
INSERT INTO custody_lines (
    custody_transaction_id,
    asset_id,
    quantity
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, custody_transaction_id, asset_id, quantity, created_at
`

type CreateCustodyLineParams struct {
	CustodyTransactionID string `json:"custody_transaction_id"`
	AssetID              string `json:"asset_id"`
	Quantity             int32  `json:"quantity"`
}

func (q *Queries) CreateCustodyLine(ctx context.Context, arg CreateCustodyLineParams) (CustodyLine, error) {
	row := q.db.QueryRow(ctx, createCustodyLine, arg.CustodyTransactionID, arg.AssetID, arg.Quantity)
	var i CustodyLine
	err := row.Scan(
		&i.ID,
		&i.CustodyTransactionID,
		&i.AssetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createCustodyTransaction = `-- name: CreateCustodyTransaction :one
INSERT INTO custody_transactions (
    id,
    transaction_type,
    personnel_id,
    operator_id,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, transaction_type, personnel_id, operator_id, notes, created_at
`

type CreateCustodyTransactionParams struct {
	ID              string `json:"id"`
	TransactionType string `json:"transaction_type"`
	PersonnelID     string `json:"personnel_id"`
	OperatorID      string `json:"operator_id"`
	Notes           string `json:"notes"`
}

func (q *Queries) CreateCustodyTransaction(ctx context.Context, arg CreateCustodyTransactionParams) (CustodyTransaction, error) {
	row := q.db.QueryRow(ctx, createCustodyTransaction,
		arg.ID,
		arg.TransactionType,
		arg.PersonnelID,
		arg.OperatorID,
		arg.Notes,
	)
	var i CustodyTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionType,
		&i.PersonnelID,
		&i.OperatorID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseCustodyBalanceIfAvailable = `-- name: DecreaseCustodyBalanceIfAvailable :one
UPDATE custody_balances
SET
    quantity = quantity - $1,
    updated_at = now()
WHERE personnel_id = $2
  AND asset_id = $3
  AND quantity >= $1
RETURNING quantity
`

type DecreaseCustodyBalanceIfAvailableParams struct {
	Quantity    int32  `json:"quantity"`
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
}

func (q *Queries) DecreaseCustodyBalanceIfAvailable(ctx context.Context, arg DecreaseCustodyBalanceIfAvailableParams) (int32, error) {
	row := q.db.QueryRow(ctx, decreaseCustodyBalanceIfAvailable, arg.Quantity, arg.PersonnelID, arg.AssetID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getCustodyBalanceQuantity = `-- name: GetCustodyBalanceQuantity :one
SELECT quantity
FROM custody_balances
WHERE personnel_id = $1
  AND asset_id = $2
`

type GetCustodyBalanceQuantityParams struct {
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
}

func (q *Queries) GetCustodyBalanceQuantity(ctx context.Context, arg GetCustodyBalanceQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCustodyBalanceQuantity, arg.PersonnelID, arg.AssetID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getCustodyCorrectionContextsByTransactionID = `-- name: GetCustodyCorrectionContextsByTransactionID :many
SELECT
    cc.id,
    cc.corrected_transaction_id,
    cc.operator_id,
    o.alias AS operator_alias,
    o.rank AS operator_rank,
    o.role AS operator_role,
    o.active AS operator_active,
    cc.corrected_personnel_id,
    p.full_name AS corrected_personnel_full_name,
    p.alias AS corrected_personnel_alias,
    p.rank AS corrected_personnel_rank,
    p.registration_id AS corrected_personnel_registration_id,
    p.active AS corrected_personnel_active,
    cc.corrected_notes,
    cc.created_at,
    ccl.asset_id,
    a.name AS asset_name,
    a.active AS asset_active,
    ccl.quantity
FROM custody_corrections cc
JOIN operators o ON o.id = cc.operator_id
JOIN personnel p ON p.id = cc.corrected_personnel_id
JOIN custody_correction_lines ccl ON ccl.custody_correction_id = cc.id
JOIN assets a ON a.id = ccl.asset_id
WHERE cc.corrected_transaction_id = $1
ORDER BY cc.created_at ASC, cc.id ASC, a.name ASC, ccl.id ASC
`

type GetCustodyCorrectionContextsByTransactionIDRow struct {
	ID                               string             `json:"id"`
	CorrectedTransactionID           string             `json:"corrected_transaction_id"`
	OperatorID                       string             `json:"operator_id"`
	OperatorAlias                    string             `json:"operator_alias"`
	OperatorRank                     string             `json:"operator_rank"`
	OperatorRole                     string             `json:"operator_role"`
	OperatorActive                   bool               `json:"operator_active"`
	CorrectedPersonnelID             string             `json:"corrected_personnel_id"`
	CorrectedPersonnelFullName       string             `json:"corrected_personnel_full_name"`
	CorrectedPersonnelAlias          string             `json:"corrected_personnel_alias"`
	CorrectedPersonnelRank           string             `json:"corrected_personnel_rank"`
	CorrectedPersonnelRegistrationID string             `json:"corrected_personnel_registration_id"`
	CorrectedPersonnelActive         bool               `json:"corrected_personnel_active"`
	CorrectedNotes                   string             `json:"corrected_notes"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	AssetID                          string             `json:"asset_id"`
	AssetName                        string             `json:"asset_name"`
	AssetActive                      bool               `json:"asset_active"`
	Quantity                         int32              `json:"quantity"`
}

func (q *Queries) GetCustodyCorrectionContextsByTransactionID(ctx context.Context, correctedTransactionID string) ([]GetCustodyCorrectionContextsByTransactionIDRow, error) {
	rows, err := q.db.Query(ctx, getCustodyCorrectionContextsByTransactionID, correctedTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustodyCorrectionContextsByTransactionIDRow{}
	for rows.Next() {
		var i GetCustodyCorrectionContextsByTransactionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CorrectedTransactionID,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.OperatorRole,
			&i.OperatorActive,
			&i.CorrectedPersonnelID,
			&i.CorrectedPersonnelFullName,
			&i.CorrectedPersonnelAlias,
			&i.CorrectedPersonnelRank,
			&i.CorrectedPersonnelRegistrationID,
			&i.CorrectedPersonnelActive,
			&i.CorrectedNotes,
			&i.CreatedAt,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustodyTransactionReceiptByID = `-- name: GetCustodyTransactionReceiptByID :many
SELECT
    ct.id,
    ct.transaction_type,
    ct.personnel_id,
    p.full_name AS personnel_full_name,
    p.alias AS personnel_alias,
    p.rank AS personnel_rank,
    p.registration_id AS personnel_registration_id,
    p.active AS personnel_active,
    ct.operator_id,
    o.alias AS operator_alias,
    o.rank AS operator_rank,
    o.role AS operator_role,
    o.active AS operator_active,
    ct.notes,
    ct.created_at,
    cl.asset_id,
    a.name AS asset_name,
    a.active AS asset_active,
    cl.quantity
FROM custody_transactions ct
JOIN personnel p ON p.id = ct.personnel_id
JOIN operators o ON o.id = ct.operator_id
JOIN custody_lines cl ON cl.custody_transaction_id = ct.id
JOIN assets a ON a.id = cl.asset_id
WHERE ct.id = $1
ORDER BY a.name ASC, cl.id ASC
`

type GetCustodyTransactionReceiptByIDRow struct {
	ID                      string             `json:"id"`
	TransactionType         string             `json:"transaction_type"`
	PersonnelID             string             `json:"personnel_id"`
	PersonnelFullName       string             `json:"personnel_full_name"`
	PersonnelAlias          string             `json:"personnel_alias"`
	PersonnelRank           string             `json:"personnel_rank"`
	PersonnelRegistrationID string             `json:"personnel_registration_id"`
	PersonnelActive         bool               `json:"personnel_active"`
	OperatorID              string             `json:"operator_id"`
	OperatorAlias           string             `json:"operator_alias"`
	OperatorRank            string             `json:"operator_rank"`
	OperatorRole            string             `json:"operator_role"`
	OperatorActive          bool               `json:"operator_active"`
	Notes                   string             `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	AssetID                 string             `json:"asset_id"`
	AssetName               string             `json:"asset_name"`
	AssetActive             bool               `json:"asset_active"`
	Quantity                int32              `json:"quantity"`
}

func (q *Queries) GetCustodyTransactionReceiptByID(ctx context.Context, id string) ([]GetCustodyTransactionReceiptByIDRow, error) {
	rows, err := q.db.Query(ctx, getCustodyTransactionReceiptByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustodyTransactionReceiptByIDRow{}
	for rows.Next() {
		var i GetCustodyTransactionReceiptByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionType,
			&i.PersonnelID,
			&i.PersonnelFullName,
			&i.PersonnelAlias,
			&i.PersonnelRank,
			&i.PersonnelRegistrationID,
			&i.PersonnelActive,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.OperatorRole,
			&i.OperatorActive,
			&i.Notes,
			&i.CreatedAt,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseCustodyBalance = `-- name: IncreaseCustodyBalance :exec
INSERT INTO custody_balances (
    personnel_id,
    asset_id,
    quantity,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    now()
)
ON CONFLICT (personnel_id, asset_id)
DO UPDATE SET
    quantity = custody_balances.quantity + EXCLUDED.quantity,
    updated_at = now()
`

type IncreaseCustodyBalanceParams struct {
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) IncreaseCustodyBalance(ctx context.Context, arg IncreaseCustodyBalanceParams) error {
	_, err := q.db.Exec(ctx, increaseCustodyBalance, arg.PersonnelID, arg.AssetID, arg.Quantity)
	return err
}

const listCurrentCustodyByAsset = `-- name: ListCurrentCustodyByAsset :many
SELECT
    cb.asset_id,
    cb.personnel_id,
    p.full_name AS personnel_full_name,
    p.alias AS personnel_alias,
    p.rank AS personnel_rank,
    p.active AS personnel_active,
    cb.quantity,
    cb.updated_at
FROM custody_balances cb
JOIN personnel p ON p.id = cb.personnel_id
WHERE cb.asset_id = $1
  AND cb.quantity > 0
ORDER BY p.full_name ASC, cb.personnel_id ASC
`

type ListCurrentCustodyByAssetRow struct {
	AssetID           string             `json:"asset_id"`
	PersonnelID       string             `json:"personnel_id"`
	PersonnelFullName string             `json:"personnel_full_name"`
	PersonnelAlias    string             `json:"personnel_alias"`
	PersonnelRank     string             `json:"personnel_rank"`
	PersonnelActive   bool               `json:"personnel_active"`
	Quantity          int32              `json:"quantity"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentCustodyByAsset(ctx context.Context, assetID string) ([]ListCurrentCustodyByAssetRow, error) {
	rows, err := q.db.Query(ctx, listCurrentCustodyByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentCustodyByAssetRow{}
	for rows.Next() {
		var i ListCurrentCustodyByAssetRow
		if err := rows.Scan(
			&i.AssetID,
			&i.PersonnelID,
			&i.PersonnelFullName,
			&i.PersonnelAlias,
			&i.PersonnelRank,
			&i.PersonnelActive,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentCustodyByPersonnel = `-- name: ListCurrentCustodyByPersonnel :many
SELECT
    cb.personnel_id,
    cb.asset_id,
    a.name AS asset_name,
    a.active AS asset_active,
    cb.quantity,
    cb.updated_at
FROM custody_balances cb
JOIN assets a ON a.id = cb.asset_id
WHERE cb.personnel_id = $1
  AND cb.quantity > 0
ORDER BY a.name ASC, cb.asset_id ASC
`

type ListCurrentCustodyByPersonnelRow struct {
	PersonnelID string             `json:"personnel_id"`
	AssetID     string             `json:"asset_id"`
	AssetName   string             `json:"asset_name"`
	AssetActive bool               `json:"asset_active"`
	Quantity    int32              `json:"quantity"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentCustodyByPersonnel(ctx context.Context, personnelID string) ([]ListCurrentCustodyByPersonnelRow, error) {
	rows, err := q.db.Query(ctx, listCurrentCustodyByPersonnel, personnelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentCustodyByPersonnelRow{}
	for rows.Next() {
		var i ListCurrentCustodyByPersonnelRow
		if err := rows.Scan(
			&i.PersonnelID,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustodyHistoryByPersonnel = `-- name: ListCustodyHistoryByPersonnel :many
WITH correction_counts AS (
    SELECT
        corrected_transaction_id,
        count(*)::int AS edit_count
    FROM custody_corrections
    GROUP BY corrected_transaction_id
),
latest_corrections AS (
    SELECT DISTINCT ON (corrected_transaction_id)
        id,
        corrected_transaction_id,
        corrected_personnel_id,
        corrected_notes
    FROM custody_corrections
    ORDER BY corrected_transaction_id, created_at DESC, id DESC
),
effective_transactions AS (
    SELECT
        ct.id,
        ct.transaction_type,
        COALESCE(lc.corrected_personnel_id, ct.personnel_id) AS effective_personnel_id,
        ct.personnel_id AS original_personnel_id,
        ct.operator_id,
        COALESCE(lc.corrected_notes, ct.notes) AS effective_notes,
        ct.created_at,
        lc.id AS latest_correction_id,
        COALESCE(cc.edit_count, 0)::int AS edit_count
    FROM custody_transactions ct
    LEFT JOIN latest_corrections lc
        ON lc.corrected_transaction_id = ct.id
    LEFT JOIN correction_counts cc
        ON cc.corrected_transaction_id = ct.id
)
SELECT
    history.transaction_id,
    history.transaction_type,
    history.personnel_id,
    history.operator_id,
    history.operator_alias,
    history.operator_rank,
    history.notes,
    history.transaction_created_at,
    history.asset_id,
    history.asset_name,
    history.asset_active,
    history.quantity,
    history.has_correction,
    history.edit_count
FROM (
    SELECT
        et.id AS transaction_id,
        et.transaction_type,
        et.effective_personnel_id AS personnel_id,
        et.operator_id,
        o.alias AS operator_alias,
        o.rank AS operator_rank,
        et.effective_notes AS notes,
        et.created_at AS transaction_created_at,
        COALESCE(ccl.asset_id, cl.asset_id) AS asset_id,
        a.name AS asset_name,
        a.active AS asset_active,
        COALESCE(ccl.quantity, cl.quantity) AS quantity,
        (et.edit_count > 0) AS has_correction,
        et.edit_count
    FROM effective_transactions et
    LEFT JOIN custody_lines cl
        ON cl.custody_transaction_id = et.id
        AND et.latest_correction_id IS NULL
    LEFT JOIN custody_correction_lines ccl
        ON ccl.custody_correction_id = et.latest_correction_id
        AND et.latest_correction_id IS NOT NULL
    JOIN assets a ON a.id = COALESCE(ccl.asset_id, cl.asset_id)
    JOIN operators o ON o.id = et.operator_id
) history
WHERE personnel_id = $1
ORDER BY transaction_created_at DESC, transaction_id DESC, asset_name ASC
LIMIT $2
`

type ListCustodyHistoryByPersonnelParams struct {
	PersonnelID string `json:"personnel_id"`
	LimitCount  int32  `json:"limit_count"`
}

type ListCustodyHistoryByPersonnelRow struct {
	TransactionID        string             `json:"transaction_id"`
	TransactionType      string             `json:"transaction_type"`
	PersonnelID          string             `json:"personnel_id"`
	OperatorID           string             `json:"operator_id"`
	OperatorAlias        string             `json:"operator_alias"`
	OperatorRank         string             `json:"operator_rank"`
	Notes                string             `json:"notes"`
	TransactionCreatedAt pgtype.Timestamptz `json:"transaction_created_at"`
	AssetID              string             `json:"asset_id"`
	AssetName            string             `json:"asset_name"`
	AssetActive          bool               `json:"asset_active"`
	Quantity             int32              `json:"quantity"`
	HasCorrection        bool               `json:"has_correction"`
	EditCount            int32              `json:"edit_count"`
}

func (q *Queries) ListCustodyHistoryByPersonnel(ctx context.Context, arg ListCustodyHistoryByPersonnelParams) ([]ListCustodyHistoryByPersonnelRow, error) {
	rows, err := q.db.Query(ctx, listCustodyHistoryByPersonnel, arg.PersonnelID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustodyHistoryByPersonnelRow{}
	for rows.Next() {
		var i ListCustodyHistoryByPersonnelRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.TransactionType,
			&i.PersonnelID,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.Notes,
			&i.TransactionCreatedAt,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
			&i.HasCorrection,
			&i.EditCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustodyTransactionLedgerPeriods = `-- name: ListCustodyTransactionLedgerPeriods :many
SELECT
    extract(year FROM created_at)::int AS year,
    extract(month FROM created_at)::int AS month,
    count(*)::int AS transaction_count
FROM custody_transactions
GROUP BY
    extract(year FROM created_at)::int,
    extract(month FROM created_at)::int
ORDER BY year DESC, month DESC
`

type ListCustodyTransactionLedgerPeriodsRow struct {
	Year             int32 `json:"year"`
	Month            int32 `json:"month"`
	TransactionCount int32 `json:"transaction_count"`
}

func (q *Queries) ListCustodyTransactionLedgerPeriods(ctx context.Context) ([]ListCustodyTransactionLedgerPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listCustodyTransactionLedgerPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustodyTransactionLedgerPeriodsRow{}
	for rows.Next() {
		var i ListCustodyTransactionLedgerPeriodsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustodyTransactionSummaries = `-- name: ListCustodyTransactionSummaries :many
WITH correction_counts AS (
    SELECT
        corrected_transaction_id,
        count(*)::int AS edit_count
    FROM custody_corrections
    GROUP BY corrected_transaction_id
),
latest_corrections AS (
    SELECT DISTINCT ON (corrected_transaction_id)
        id,
        corrected_transaction_id,
        corrected_personnel_id
    FROM custody_corrections
    ORDER BY corrected_transaction_id, created_at DESC, id DESC
),
effective_transactions AS (
    SELECT
        ct.id,
        row_number() OVER (ORDER BY ct.created_at ASC, ct.id ASC)::int AS sequence_number,
        ct.transaction_type,
        ct.personnel_id AS original_personnel_id,
        COALESCE(lc.corrected_personnel_id, ct.personnel_id) AS effective_personnel_id,
        ct.operator_id,
        ct.created_at,
        lc.id AS latest_correction_id,
        COALESCE(cc.edit_count, 0)::int AS edit_count
    FROM custody_transactions ct
    LEFT JOIN latest_corrections lc
        ON lc.corrected_transaction_id = ct.id
    LEFT JOIN correction_counts cc
        ON cc.corrected_transaction_id = ct.id
),
effective_lines AS (
    SELECT
        et.id AS transaction_id,
        cl.id AS line_order,
        cl.asset_id,
        a.name AS asset_name,
        a.active AS asset_active,
        cl.quantity
    FROM effective_transactions et
    JOIN custody_lines cl
        ON cl.custody_transaction_id = et.id
    JOIN assets a
        ON a.id = cl.asset_id
    WHERE et.latest_correction_id IS NULL

    UNION ALL

    SELECT
        et.id AS transaction_id,
        ccl.id AS line_order,
        ccl.asset_id,
        a.name AS asset_name,
        a.active AS asset_active,
        ccl.quantity
    FROM effective_transactions et
    JOIN custody_correction_lines ccl
        ON ccl.custody_correction_id = et.latest_correction_id
    JOIN assets a
        ON a.id = ccl.asset_id
    WHERE et.latest_correction_id IS NOT NULL
),
line_totals AS (
    SELECT
        transaction_id,
        sum(quantity)::int AS total_quantity
    FROM effective_lines
    GROUP BY transaction_id
),
filtered_transactions AS (
    SELECT et.id, et.sequence_number, et.transaction_type, et.original_personnel_id, et.effective_personnel_id, et.operator_id, et.created_at, et.latest_correction_id, et.edit_count
    FROM effective_transactions et
    JOIN personnel op
        ON op.id = et.original_personnel_id
    JOIN personnel ep
        ON ep.id = et.effective_personnel_id
    JOIN operators o
        ON o.id = et.operator_id
    WHERE (
        NOT $1::bool
        OR (
            et.created_at >= $2::timestamptz
            AND et.created_at < $3::timestamptz
        )
    )
    AND (
        $4::text = 'all'
        OR et.transaction_type = $4::text
    )
    AND (
        $5::text = 'all'
        OR (
            $5::text = 'edited'
            AND et.edit_count > 0
        )
        OR (
            $5::text = 'unedited'
            AND et.edit_count = 0
        )
    )
    AND (
        $6::text = ''
        OR et.id ILIKE $6::text ESCAPE '\'
        OR ep.full_name ILIKE $6::text ESCAPE '\'
        OR ep.alias ILIKE $6::text ESCAPE '\'
        OR ep.registration_id ILIKE $6::text ESCAPE '\'
        OR op.full_name ILIKE $6::text ESCAPE '\'
        OR op.alias ILIKE $6::text ESCAPE '\'
        OR op.registration_id ILIKE $6::text ESCAPE '\'
        OR o.alias ILIKE $6::text ESCAPE '\'
        OR EXISTS (
            SELECT 1
            FROM effective_lines el
            WHERE el.transaction_id = et.id
              AND el.asset_name ILIKE $6::text ESCAPE '\'
        )
    )
),
selected_transactions AS (
    SELECT id, sequence_number, transaction_type, original_personnel_id, effective_personnel_id, operator_id, created_at, latest_correction_id, edit_count
    FROM filtered_transactions
    ORDER BY created_at DESC, id DESC
    LIMIT $8
    OFFSET $7
)
SELECT
    st.id,
    st.sequence_number,
    st.transaction_type,

    op.id AS original_personnel_id,
    op.full_name AS original_personnel_full_name,
    op.alias AS original_personnel_alias,
    op.rank AS original_personnel_rank,
    op.active AS original_personnel_active,

    ep.id AS effective_personnel_id,
    ep.full_name AS effective_personnel_full_name,
    ep.alias AS effective_personnel_alias,
    ep.rank AS effective_personnel_rank,
    ep.active AS effective_personnel_active,

    st.operator_id,
    o.alias AS operator_alias,
    o.rank AS operator_rank,
    o.role AS operator_role,
    o.active AS operator_active,

    COALESCE(lt.total_quantity, 0)::int AS total_quantity,
    st.created_at,
    (st.edit_count > 0) AS has_correction,
    st.edit_count,

    el.asset_id,
    el.asset_name,
    el.asset_active,
    el.quantity
FROM selected_transactions st
JOIN personnel op ON op.id = st.original_personnel_id
JOIN personnel ep ON ep.id = st.effective_personnel_id
JOIN operators o ON o.id = st.operator_id
LEFT JOIN line_totals lt ON lt.transaction_id = st.id
LEFT JOIN effective_lines el ON el.transaction_id = st.id
ORDER BY st.created_at DESC, st.id DESC, el.asset_name ASC, el.line_order ASC
`

type ListCustodyTransactionSummariesParams struct {
	HasPeriod             bool               `json:"has_period"`
	PeriodStart           pgtype.Timestamptz `json:"period_start"`
	PeriodEnd             pgtype.Timestamptz `json:"period_end"`
	TransactionTypeFilter string             `json:"transaction_type_filter"`
	EditStatusFilter      string             `json:"edit_status_filter"`
	SearchPattern         string             `json:"search_pattern"`
	OffsetCount           int32              `json:"offset_count"`
	PageSizePlusOne       int32              `json:"page_size_plus_one"`
}

type ListCustodyTransactionSummariesRow struct {
	ID                         string             `json:"id"`
	SequenceNumber             int32              `json:"sequence_number"`
	TransactionType            string             `json:"transaction_type"`
	OriginalPersonnelID        string             `json:"original_personnel_id"`
	OriginalPersonnelFullName  string             `json:"original_personnel_full_name"`
	OriginalPersonnelAlias     string             `json:"original_personnel_alias"`
	OriginalPersonnelRank      string             `json:"original_personnel_rank"`
	OriginalPersonnelActive    bool               `json:"original_personnel_active"`
	EffectivePersonnelID       string             `json:"effective_personnel_id"`
	EffectivePersonnelFullName string             `json:"effective_personnel_full_name"`
	EffectivePersonnelAlias    string             `json:"effective_personnel_alias"`
	EffectivePersonnelRank     string             `json:"effective_personnel_rank"`
	EffectivePersonnelActive   bool               `json:"effective_personnel_active"`
	OperatorID                 string             `json:"operator_id"`
	OperatorAlias              string             `json:"operator_alias"`
	OperatorRank               string             `json:"operator_rank"`
	OperatorRole               string             `json:"operator_role"`
	OperatorActive             bool               `json:"operator_active"`
	TotalQuantity              int32              `json:"total_quantity"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	HasCorrection              bool               `json:"has_correction"`
	EditCount                  int32              `json:"edit_count"`
	AssetID                    pgtype.Text        `json:"asset_id"`
	AssetName                  pgtype.Text        `json:"asset_name"`
	AssetActive                pgtype.Bool        `json:"asset_active"`
	Quantity                   pgtype.Int4        `json:"quantity"`
}

func (q *Queries) ListCustodyTransactionSummaries(ctx context.Context, arg ListCustodyTransactionSummariesParams) ([]ListCustodyTransactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, listCustodyTransactionSummaries,
		arg.HasPeriod,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TransactionTypeFilter,
		arg.EditStatusFilter,
		arg.SearchPattern,
		arg.OffsetCount,
		arg.PageSizePlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustodyTransactionSummariesRow{}
	for rows.Next() {
		var i ListCustodyTransactionSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.SequenceNumber,
			&i.TransactionType,
			&i.OriginalPersonnelID,
			&i.OriginalPersonnelFullName,
			&i.OriginalPersonnelAlias,
			&i.OriginalPersonnelRank,
			&i.OriginalPersonnelActive,
			&i.EffectivePersonnelID,
			&i.EffectivePersonnelFullName,
			&i.EffectivePersonnelAlias,
			&i.EffectivePersonnelRank,
			&i.EffectivePersonnelActive,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.OperatorRole,
			&i.OperatorActive,
			&i.TotalQuantity,
			&i.CreatedAt,
			&i.HasCorrection,
			&i.EditCount,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonnelWithCurrentCustody = `-- name: ListPersonnelWithCurrentCustody :many
SELECT
    p.id,
    p.full_name,
    p.alias,
    p.rank,
    p.registration_id,
    p.active,
    sum(cb.quantity)::int AS total_quantity
FROM custody_balances cb
JOIN personnel p ON p.id = cb.personnel_id
WHERE cb.quantity > 0
GROUP BY
    p.id,
    p.full_name,
    p.alias,
    p.rank,
    p.registration_id,
    p.active
ORDER BY p.active DESC, p.rank ASC, p.alias ASC, p.full_name ASC
`

type ListPersonnelWithCurrentCustodyRow struct {
	ID             string `json:"id"`
	FullName       string `json:"full_name"`
	Alias          string `json:"alias"`
	Rank           string `json:"rank"`
	RegistrationID string `json:"registration_id"`
	Active         bool   `json:"active"`
	TotalQuantity  int32  `json:"total_quantity"`
}

func (q *Queries) ListPersonnelWithCurrentCustody(ctx context.Context) ([]ListPersonnelWithCurrentCustodyRow, error) {
	rows, err := q.db.Query(ctx, listPersonnelWithCurrentCustody)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonnelWithCurrentCustodyRow{}
	for rows.Next() {
		var i ListPersonnelWithCurrentCustodyRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Alias,
			&i.Rank,
			&i.RegistrationID,
			&i.Active,
			&i.TotalQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
