// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custody.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustodyLine = `-- name: CreateCustodyLine :one
INSERT INTO custody_lines (
    custody_transaction_id,
    asset_id,
    quantity
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, custody_transaction_id, asset_id, quantity, created_at
`

type CreateCustodyLineParams struct {
	CustodyTransactionID string `json:"custody_transaction_id"`
	AssetID              string `json:"asset_id"`
	Quantity             int32  `json:"quantity"`
}

func (q *Queries) CreateCustodyLine(ctx context.Context, arg CreateCustodyLineParams) (CustodyLine, error) {
	row := q.db.QueryRow(ctx, createCustodyLine, arg.CustodyTransactionID, arg.AssetID, arg.Quantity)
	var i CustodyLine
	err := row.Scan(
		&i.ID,
		&i.CustodyTransactionID,
		&i.AssetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createCustodyTransaction = `-- name: CreateCustodyTransaction :one
INSERT INTO custody_transactions (
    id,
    transaction_type,
    personnel_id,
    operator_id,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, transaction_type, personnel_id, operator_id, notes, created_at
`

type CreateCustodyTransactionParams struct {
	ID              string `json:"id"`
	TransactionType string `json:"transaction_type"`
	PersonnelID     string `json:"personnel_id"`
	OperatorID      string `json:"operator_id"`
	Notes           string `json:"notes"`
}

func (q *Queries) CreateCustodyTransaction(ctx context.Context, arg CreateCustodyTransactionParams) (CustodyTransaction, error) {
	row := q.db.QueryRow(ctx, createCustodyTransaction,
		arg.ID,
		arg.TransactionType,
		arg.PersonnelID,
		arg.OperatorID,
		arg.Notes,
	)
	var i CustodyTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionType,
		&i.PersonnelID,
		&i.OperatorID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseCustodyBalanceIfAvailable = `-- name: DecreaseCustodyBalanceIfAvailable :one
UPDATE custody_balances
SET
    quantity = quantity - $1,
    updated_at = now()
WHERE personnel_id = $2
  AND asset_id = $3
  AND quantity >= $1
RETURNING quantity
`

type DecreaseCustodyBalanceIfAvailableParams struct {
	Quantity    int32  `json:"quantity"`
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
}

func (q *Queries) DecreaseCustodyBalanceIfAvailable(ctx context.Context, arg DecreaseCustodyBalanceIfAvailableParams) (int32, error) {
	row := q.db.QueryRow(ctx, decreaseCustodyBalanceIfAvailable, arg.Quantity, arg.PersonnelID, arg.AssetID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getCustodyBalanceQuantity = `-- name: GetCustodyBalanceQuantity :one
SELECT quantity
FROM custody_balances
WHERE personnel_id = $1
  AND asset_id = $2
`

type GetCustodyBalanceQuantityParams struct {
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
}

func (q *Queries) GetCustodyBalanceQuantity(ctx context.Context, arg GetCustodyBalanceQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCustodyBalanceQuantity, arg.PersonnelID, arg.AssetID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getCustodyCorrectionContextsByTransactionID = `-- name: GetCustodyCorrectionContextsByTransactionID :many
SELECT
    cc.id,
    cc.corrected_transaction_id,
    cc.operator_id,
    o.alias AS operator_alias,
    o.rank AS operator_rank,
    o.role AS operator_role,
    o.active AS operator_active,
    cc.corrected_personnel_id,
    p.full_name AS corrected_personnel_full_name,
    p.alias AS corrected_personnel_alias,
    p.rank AS corrected_personnel_rank,
    p.registration_id AS corrected_personnel_registration_id,
    p.active AS corrected_personnel_active,
    cc.corrected_notes,
    cc.created_at,
    ccl.asset_id,
    a.name AS asset_name,
    a.active AS asset_active,
    ccl.quantity
FROM custody_corrections cc
JOIN operators o ON o.id = cc.operator_id
JOIN personnel p ON p.id = cc.corrected_personnel_id
JOIN custody_correction_lines ccl ON ccl.custody_correction_id = cc.id
JOIN assets a ON a.id = ccl.asset_id
WHERE cc.corrected_transaction_id = $1
ORDER BY cc.created_at ASC, cc.id ASC, a.name ASC, ccl.id ASC
`

type GetCustodyCorrectionContextsByTransactionIDRow struct {
	ID                               string             `json:"id"`
	CorrectedTransactionID           string             `json:"corrected_transaction_id"`
	OperatorID                       string             `json:"operator_id"`
	OperatorAlias                    string             `json:"operator_alias"`
	OperatorRank                     string             `json:"operator_rank"`
	OperatorRole                     string             `json:"operator_role"`
	OperatorActive                   bool               `json:"operator_active"`
	CorrectedPersonnelID             string             `json:"corrected_personnel_id"`
	CorrectedPersonnelFullName       string             `json:"corrected_personnel_full_name"`
	CorrectedPersonnelAlias          string             `json:"corrected_personnel_alias"`
	CorrectedPersonnelRank           string             `json:"corrected_personnel_rank"`
	CorrectedPersonnelRegistrationID string             `json:"corrected_personnel_registration_id"`
	CorrectedPersonnelActive         bool               `json:"corrected_personnel_active"`
	CorrectedNotes                   string             `json:"corrected_notes"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	AssetID                          string             `json:"asset_id"`
	AssetName                        string             `json:"asset_name"`
	AssetActive                      bool               `json:"asset_active"`
	Quantity                         int32              `json:"quantity"`
}

func (q *Queries) GetCustodyCorrectionContextsByTransactionID(ctx context.Context, correctedTransactionID string) ([]GetCustodyCorrectionContextsByTransactionIDRow, error) {
	rows, err := q.db.Query(ctx, getCustodyCorrectionContextsByTransactionID, correctedTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustodyCorrectionContextsByTransactionIDRow{}
	for rows.Next() {
		var i GetCustodyCorrectionContextsByTransactionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CorrectedTransactionID,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.OperatorRole,
			&i.OperatorActive,
			&i.CorrectedPersonnelID,
			&i.CorrectedPersonnelFullName,
			&i.CorrectedPersonnelAlias,
			&i.CorrectedPersonnelRank,
			&i.CorrectedPersonnelRegistrationID,
			&i.CorrectedPersonnelActive,
			&i.CorrectedNotes,
			&i.CreatedAt,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustodyTransactionReceiptByID = `-- name: GetCustodyTransactionReceiptByID :many
SELECT
    ct.id,
    ct.transaction_type,
    ct.personnel_id,
    p.full_name AS personnel_full_name,
    p.alias AS personnel_alias,
    p.rank AS personnel_rank,
    p.registration_id AS personnel_registration_id,
    p.active AS personnel_active,
    ct.operator_id,
    o.alias AS operator_alias,
    o.rank AS operator_rank,
    o.role AS operator_role,
    o.active AS operator_active,
    ct.notes,
    ct.created_at,
    cl.asset_id,
    a.name AS asset_name,
    a.active AS asset_active,
    cl.quantity
FROM custody_transactions ct
JOIN personnel p ON p.id = ct.personnel_id
JOIN operators o ON o.id = ct.operator_id
JOIN custody_lines cl ON cl.custody_transaction_id = ct.id
JOIN assets a ON a.id = cl.asset_id
WHERE ct.id = $1
ORDER BY a.name ASC, cl.id ASC
`

type GetCustodyTransactionReceiptByIDRow struct {
	ID                      string             `json:"id"`
	TransactionType         string             `json:"transaction_type"`
	PersonnelID             string             `json:"personnel_id"`
	PersonnelFullName       string             `json:"personnel_full_name"`
	PersonnelAlias          string             `json:"personnel_alias"`
	PersonnelRank           string             `json:"personnel_rank"`
	PersonnelRegistrationID string             `json:"personnel_registration_id"`
	PersonnelActive         bool               `json:"personnel_active"`
	OperatorID              string             `json:"operator_id"`
	OperatorAlias           string             `json:"operator_alias"`
	OperatorRank            string             `json:"operator_rank"`
	OperatorRole            string             `json:"operator_role"`
	OperatorActive          bool               `json:"operator_active"`
	Notes                   string             `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	AssetID                 string             `json:"asset_id"`
	AssetName               string             `json:"asset_name"`
	AssetActive             bool               `json:"asset_active"`
	Quantity                int32              `json:"quantity"`
}

func (q *Queries) GetCustodyTransactionReceiptByID(ctx context.Context, id string) ([]GetCustodyTransactionReceiptByIDRow, error) {
	rows, err := q.db.Query(ctx, getCustodyTransactionReceiptByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustodyTransactionReceiptByIDRow{}
	for rows.Next() {
		var i GetCustodyTransactionReceiptByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionType,
			&i.PersonnelID,
			&i.PersonnelFullName,
			&i.PersonnelAlias,
			&i.PersonnelRank,
			&i.PersonnelRegistrationID,
			&i.PersonnelActive,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.OperatorRole,
			&i.OperatorActive,
			&i.Notes,
			&i.CreatedAt,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseCustodyBalance = `-- name: IncreaseCustodyBalance :exec
INSERT INTO custody_balances (
    personnel_id,
    asset_id,
    quantity,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    now()
)
ON CONFLICT (personnel_id, asset_id)
DO UPDATE SET
    quantity = custody_balances.quantity + EXCLUDED.quantity,
    updated_at = now()
`

type IncreaseCustodyBalanceParams struct {
	PersonnelID string `json:"personnel_id"`
	AssetID     string `json:"asset_id"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) IncreaseCustodyBalance(ctx context.Context, arg IncreaseCustodyBalanceParams) error {
	_, err := q.db.Exec(ctx, increaseCustodyBalance, arg.PersonnelID, arg.AssetID, arg.Quantity)
	return err
}

const listCurrentCustodyByAsset = `-- name: ListCurrentCustodyByAsset :many
SELECT
    cb.asset_id,
    cb.personnel_id,
    p.full_name AS personnel_full_name,
    p.alias AS personnel_alias,
    p.rank AS personnel_rank,
    p.active AS personnel_active,
    cb.quantity,
    cb.updated_at
FROM custody_balances cb
JOIN personnel p ON p.id = cb.personnel_id
WHERE cb.asset_id = $1
  AND cb.quantity > 0
ORDER BY p.full_name ASC, cb.personnel_id ASC
`

type ListCurrentCustodyByAssetRow struct {
	AssetID           string             `json:"asset_id"`
	PersonnelID       string             `json:"personnel_id"`
	PersonnelFullName string             `json:"personnel_full_name"`
	PersonnelAlias    string             `json:"personnel_alias"`
	PersonnelRank     string             `json:"personnel_rank"`
	PersonnelActive   bool               `json:"personnel_active"`
	Quantity          int32              `json:"quantity"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentCustodyByAsset(ctx context.Context, assetID string) ([]ListCurrentCustodyByAssetRow, error) {
	rows, err := q.db.Query(ctx, listCurrentCustodyByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentCustodyByAssetRow{}
	for rows.Next() {
		var i ListCurrentCustodyByAssetRow
		if err := rows.Scan(
			&i.AssetID,
			&i.PersonnelID,
			&i.PersonnelFullName,
			&i.PersonnelAlias,
			&i.PersonnelRank,
			&i.PersonnelActive,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentCustodyByPersonnel = `-- name: ListCurrentCustodyByPersonnel :many
SELECT
    cb.personnel_id,
    cb.asset_id,
    a.name AS asset_name,
    a.active AS asset_active,
    cb.quantity,
    cb.updated_at
FROM custody_balances cb
JOIN assets a ON a.id = cb.asset_id
WHERE cb.personnel_id = $1
  AND cb.quantity > 0
ORDER BY a.name ASC, cb.asset_id ASC
`

type ListCurrentCustodyByPersonnelRow struct {
	PersonnelID string             `json:"personnel_id"`
	AssetID     string             `json:"asset_id"`
	AssetName   string             `json:"asset_name"`
	AssetActive bool               `json:"asset_active"`
	Quantity    int32              `json:"quantity"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentCustodyByPersonnel(ctx context.Context, personnelID string) ([]ListCurrentCustodyByPersonnelRow, error) {
	rows, err := q.db.Query(ctx, listCurrentCustodyByPersonnel, personnelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentCustodyByPersonnelRow{}
	for rows.Next() {
		var i ListCurrentCustodyByPersonnelRow
		if err := rows.Scan(
			&i.PersonnelID,
			&i.AssetID,
			&i.AssetName,
			&i.AssetActive,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustodyHistoryByPersonnel = `-- name: ListCustodyHistoryByPersonnel :many
WITH recent_transactions AS (
    SELECT
        id,
        transaction_type,
        personnel_id,
        operator_id,
        notes,
        created_at
    FROM custody_transactions
    WHERE personnel_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT $2
)
SELECT
    rt.id AS transaction_id,
    rt.transaction_type,
    rt.personnel_id,
    rt.operator_id,
    o.alias AS operator_alias,
    o.rank AS operator_rank,
    rt.notes,
    rt.created_at AS transaction_created_at,
    cl.asset_id,
    a.name AS asset_name,
    cl.quantity
FROM recent_transactions rt
JOIN custody_lines cl ON cl.custody_transaction_id = rt.id
JOIN assets a ON a.id = cl.asset_id
JOIN operators o ON o.id = rt.operator_id
ORDER BY rt.created_at DESC, rt.id DESC, cl.id ASC
`

type ListCustodyHistoryByPersonnelParams struct {
	PersonnelID string `json:"personnel_id"`
	LimitCount  int32  `json:"limit_count"`
}

type ListCustodyHistoryByPersonnelRow struct {
	TransactionID        string             `json:"transaction_id"`
	TransactionType      string             `json:"transaction_type"`
	PersonnelID          string             `json:"personnel_id"`
	OperatorID           string             `json:"operator_id"`
	OperatorAlias        string             `json:"operator_alias"`
	OperatorRank         string             `json:"operator_rank"`
	Notes                string             `json:"notes"`
	TransactionCreatedAt pgtype.Timestamptz `json:"transaction_created_at"`
	AssetID              string             `json:"asset_id"`
	AssetName            string             `json:"asset_name"`
	Quantity             int32              `json:"quantity"`
}

func (q *Queries) ListCustodyHistoryByPersonnel(ctx context.Context, arg ListCustodyHistoryByPersonnelParams) ([]ListCustodyHistoryByPersonnelRow, error) {
	rows, err := q.db.Query(ctx, listCustodyHistoryByPersonnel, arg.PersonnelID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustodyHistoryByPersonnelRow{}
	for rows.Next() {
		var i ListCustodyHistoryByPersonnelRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.TransactionType,
			&i.PersonnelID,
			&i.OperatorID,
			&i.OperatorAlias,
			&i.OperatorRank,
			&i.Notes,
			&i.TransactionCreatedAt,
			&i.AssetID,
			&i.AssetName,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
