// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CustodyBalance struct {
	PersonnelID string             `json:"personnel_id"`
	AssetID     string             `json:"asset_id"`
	Quantity    int32              `json:"quantity"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CustodyLine struct {
	ID                   int64              `json:"id"`
	CustodyTransactionID string             `json:"custody_transaction_id"`
	AssetID              string             `json:"asset_id"`
	Quantity             int32              `json:"quantity"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type CustodyTransaction struct {
	ID              string             `json:"id"`
	TransactionType string             `json:"transaction_type"`
	PersonnelID     string             `json:"personnel_id"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Personnel struct {
	ID        string             `json:"id"`
	FullName  string             `json:"full_name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
