// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID              string             `json:"id"`
	ActorOperatorID pgtype.Text        `json:"actor_operator_id"`
	EventType       string             `json:"event_type"`
	EntityType      string             `json:"entity_type"`
	EntityID        string             `json:"entity_id"`
	Outcome         string             `json:"outcome"`
	Metadata        []byte             `json:"metadata"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type CustodyBalance struct {
	PersonnelID string             `json:"personnel_id"`
	AssetID     string             `json:"asset_id"`
	Quantity    int32              `json:"quantity"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CustodyCorrection struct {
	ID                     string             `json:"id"`
	CorrectedTransactionID string             `json:"corrected_transaction_id"`
	OperatorID             string             `json:"operator_id"`
	CorrectedPersonnelID   string             `json:"corrected_personnel_id"`
	CorrectedNotes         string             `json:"corrected_notes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type CustodyCorrectionLine struct {
	ID                  int64              `json:"id"`
	CustodyCorrectionID string             `json:"custody_correction_id"`
	AssetID             string             `json:"asset_id"`
	Quantity            int32              `json:"quantity"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type CustodyLine struct {
	ID                   int64              `json:"id"`
	CustodyTransactionID string             `json:"custody_transaction_id"`
	AssetID              string             `json:"asset_id"`
	Quantity             int32              `json:"quantity"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type CustodyTransaction struct {
	ID              string             `json:"id"`
	TransactionType string             `json:"transaction_type"`
	PersonnelID     string             `json:"personnel_id"`
	OperatorID      string             `json:"operator_id"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Operator struct {
	ID             string             `json:"id"`
	RegistrationID string             `json:"registration_id"`
	Alias          string             `json:"alias"`
	Rank           string             `json:"rank"`
	Role           string             `json:"role"`
	PasswordHash   string             `json:"password_hash"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OperatorSession struct {
	ID         string             `json:"id"`
	OperatorID string             `json:"operator_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CsrfToken  string             `json:"csrf_token"`
}

type Personnel struct {
	ID               string             `json:"id"`
	FullName         string             `json:"full_name"`
	Alias            string             `json:"alias"`
	Rank             string             `json:"rank"`
	RegistrationID   string             `json:"registration_id"`
	Section          string             `json:"section"`
	OrganizationUnit string             `json:"organization_unit"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
