// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operators.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeOperatorRole = `-- name: ChangeOperatorRole :one
WITH locked_active_admins AS (
    SELECT id
    FROM operators
    WHERE role = 'admin'
      AND active = true
    FOR UPDATE
),
active_admin_count AS (
    SELECT count(*) AS value
    FROM locked_active_admins
),
updated AS (
    UPDATE operators
    SET
        role = $1::text,
        updated_at = now()
    WHERE operators.id = $2
      AND NOT (
          operators.role = 'admin'
          AND operators.active = true
          AND $1::text <> 'admin'
          AND (SELECT value FROM active_admin_count) <= 1
      )
    RETURNING operators.id
)
SELECT count(*)::int
FROM updated
`

type ChangeOperatorRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) ChangeOperatorRole(ctx context.Context, arg ChangeOperatorRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, changeOperatorRole, arg.Role, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveAdminOperators = `-- name: CountActiveAdminOperators :one
SELECT count(*)::int
FROM operators
WHERE role = 'admin'
  AND active = true
`

func (q *Queries) CountActiveAdminOperators(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveAdminOperators)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createOperator = `-- name: CreateOperator :exec
INSERT INTO operators (
    id,
    registration_id,
    alias,
    rank,
    role,
    password_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateOperatorParams struct {
	ID             string `json:"id"`
	RegistrationID string `json:"registration_id"`
	Alias          string `json:"alias"`
	Rank           string `json:"rank"`
	Role           string `json:"role"`
	PasswordHash   string `json:"password_hash"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) error {
	_, err := q.db.Exec(ctx, createOperator,
		arg.ID,
		arg.RegistrationID,
		arg.Alias,
		arg.Rank,
		arg.Role,
		arg.PasswordHash,
	)
	return err
}

const deactivateOperator = `-- name: DeactivateOperator :one
WITH locked_active_admins AS (
    SELECT id
    FROM operators
    WHERE role = 'admin'
      AND active = true
    FOR UPDATE
),
active_admin_count AS (
    SELECT count(*) AS value
    FROM locked_active_admins
),
updated AS (
    UPDATE operators
    SET
        active = false,
        updated_at = now()
    WHERE operators.id = $1
      AND operators.active = true
      AND NOT (
          operators.role = 'admin'
          AND (SELECT value FROM active_admin_count) <= 1
      )
    RETURNING operators.id
)
SELECT count(*)::int
FROM updated
`

func (q *Queries) DeactivateOperator(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, deactivateOperator, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOperatorByID = `-- name: GetOperatorByID :one
SELECT
    id,
    registration_id,
    alias,
    rank,
    role,
    password_hash,
    active,
    created_at,
    updated_at
FROM operators
WHERE id = $1
`

func (q *Queries) GetOperatorByID(ctx context.Context, id string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByID, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Alias,
		&i.Rank,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorByRegistrationID = `-- name: GetOperatorByRegistrationID :one
SELECT
    id,
    registration_id,
    alias,
    rank,
    role,
    password_hash,
    active,
    created_at,
    updated_at
FROM operators
WHERE registration_id = $1
`

func (q *Queries) GetOperatorByRegistrationID(ctx context.Context, registrationID string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByRegistrationID, registrationID)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Alias,
		&i.Rank,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorSummaryByID = `-- name: GetOperatorSummaryByID :one
SELECT
    id,
    registration_id,
    alias,
    rank,
    role,
    active,
    created_at
FROM operators
WHERE id = $1
`

type GetOperatorSummaryByIDRow struct {
	ID             string             `json:"id"`
	RegistrationID string             `json:"registration_id"`
	Alias          string             `json:"alias"`
	Rank           string             `json:"rank"`
	Role           string             `json:"role"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOperatorSummaryByID(ctx context.Context, id string) (GetOperatorSummaryByIDRow, error) {
	row := q.db.QueryRow(ctx, getOperatorSummaryByID, id)
	var i GetOperatorSummaryByIDRow
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Alias,
		&i.Rank,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listOperators = `-- name: ListOperators :many
SELECT
    id,
    registration_id,
    alias,
    rank,
    role,
    active,
    created_at
FROM operators
WHERE (
    $1::text = 'all'
    OR ($1::text = 'active' AND active = true)
    OR ($1::text = 'inactive' AND active = false)
)
AND (
    $2::text = ''
    OR alias ILIKE $2::text ESCAPE '\'
    OR registration_id ILIKE $2::text ESCAPE '\'
    OR rank ILIKE $2::text ESCAPE '\'
    OR role ILIKE $2::text ESCAPE '\'
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOperatorsParams struct {
	StatusFilter  string `json:"status_filter"`
	SearchPattern string `json:"search_pattern"`
	LimitCount    int32  `json:"limit_count"`
}

type ListOperatorsRow struct {
	ID             string             `json:"id"`
	RegistrationID string             `json:"registration_id"`
	Alias          string             `json:"alias"`
	Rank           string             `json:"rank"`
	Role           string             `json:"role"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOperators(ctx context.Context, arg ListOperatorsParams) ([]ListOperatorsRow, error) {
	rows, err := q.db.Query(ctx, listOperators, arg.StatusFilter, arg.SearchPattern, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorsRow{}
	for rows.Next() {
		var i ListOperatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Alias,
			&i.Rank,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateOperator = `-- name: ReactivateOperator :one
WITH updated AS (
    UPDATE operators
    SET
        active = true,
        updated_at = now()
    WHERE id = $1
      AND active = false
    RETURNING id
)
SELECT count(*)::int
FROM updated
`

func (q *Queries) ReactivateOperator(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, reactivateOperator, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateOperatorPasswordHash = `-- name: UpdateOperatorPasswordHash :one
WITH updated AS (
    UPDATE operators
    SET
        password_hash = $1,
        updated_at = now()
    WHERE id = $2
      AND active = true
    RETURNING id
)
SELECT count(*)::int
FROM updated
`

type UpdateOperatorPasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateOperatorPasswordHash(ctx context.Context, arg UpdateOperatorPasswordHashParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateOperatorPasswordHash, arg.PasswordHash, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
