// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperatorSession = `-- name: CreateOperatorSession :exec
INSERT INTO operator_sessions (
    id,
    operator_id,
    token_hash,
    csrf_token,
    expires_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateOperatorSessionParams struct {
	ID         string             `json:"id"`
	OperatorID string             `json:"operator_id"`
	TokenHash  string             `json:"token_hash"`
	CsrfToken  string             `json:"csrf_token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOperatorSession(ctx context.Context, arg CreateOperatorSessionParams) error {
	_, err := q.db.Exec(ctx, createOperatorSession,
		arg.ID,
		arg.OperatorID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOperatorSessions = `-- name: DeleteExpiredOperatorSessions :exec
DELETE FROM operator_sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredOperatorSessions(ctx context.Context, now pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredOperatorSessions, now)
	return err
}

const deleteOperatorSessionByTokenHash = `-- name: DeleteOperatorSessionByTokenHash :exec
DELETE FROM operator_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteOperatorSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteOperatorSessionByTokenHash, tokenHash)
	return err
}

const getOperatorSessionByTokenHash = `-- name: GetOperatorSessionByTokenHash :one
SELECT
    id,
    operator_id,
    token_hash,
    csrf_token,
    expires_at,
    created_at
FROM operator_sessions
WHERE token_hash = $1
`

type GetOperatorSessionByTokenHashRow struct {
	ID         string             `json:"id"`
	OperatorID string             `json:"operator_id"`
	TokenHash  string             `json:"token_hash"`
	CsrfToken  string             `json:"csrf_token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOperatorSessionByTokenHash(ctx context.Context, tokenHash string) (GetOperatorSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getOperatorSessionByTokenHash, tokenHash)
	var i GetOperatorSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
