// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operators.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperator = `-- name: CreateOperator :exec
INSERT INTO operators (
    id,
    username,
    role,
    password_hash
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateOperatorParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) error {
	_, err := q.db.Exec(ctx, createOperator,
		arg.ID,
		arg.Username,
		arg.Role,
		arg.PasswordHash,
	)
	return err
}

const getOperatorByID = `-- name: GetOperatorByID :one
SELECT
    id,
    username,
    role,
    password_hash,
    active,
    created_at,
    updated_at
FROM operators
WHERE id = $1
`

func (q *Queries) GetOperatorByID(ctx context.Context, id string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByID, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorByUsername = `-- name: GetOperatorByUsername :one
SELECT
    id,
    username,
    role,
    password_hash,
    active,
    created_at,
    updated_at
FROM operators
WHERE username = $1
`

func (q *Queries) GetOperatorByUsername(ctx context.Context, username string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByUsername, username)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperators = `-- name: ListOperators :many
SELECT
    id,
    username,
    role,
    active,
    created_at
FROM operators
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListOperatorsRow struct {
	ID        string             `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOperators(ctx context.Context, limitCount int32) ([]ListOperatorsRow, error) {
	rows, err := q.db.Query(ctx, listOperators, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorsRow{}
	for rows.Next() {
		var i ListOperatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
