// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operators.sql

package db

import (
	"context"
)

const createOperator = `-- name: CreateOperator :exec
INSERT INTO operators (
    id,
    username,
    password_hash
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateOperatorParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) error {
	_, err := q.db.Exec(ctx, createOperator, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const getOperatorByID = `-- name: GetOperatorByID :one
SELECT
    id,
    username,
    password_hash,
    active,
    created_at,
    updated_at
FROM operators
WHERE id = $1
`

func (q *Queries) GetOperatorByID(ctx context.Context, id string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByID, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorByUsername = `-- name: GetOperatorByUsername :one
SELECT
    id,
    username,
    password_hash,
    active,
    created_at,
    updated_at
FROM operators
WHERE username = $1
`

func (q *Queries) GetOperatorByUsername(ctx context.Context, username string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByUsername, username)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
