// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personnel.sql

package db

import (
	"context"
)

const createPersonnel = `-- name: CreatePersonnel :one
INSERT INTO personnel (
    id,
    full_name,
    active
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, full_name, active, created_at, updated_at
`

type CreatePersonnelParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	Active   bool   `json:"active"`
}

func (q *Queries) CreatePersonnel(ctx context.Context, arg CreatePersonnelParams) (Personnel, error) {
	row := q.db.QueryRow(ctx, createPersonnel, arg.ID, arg.FullName, arg.Active)
	var i Personnel
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonnel = `-- name: GetPersonnel :one
SELECT id, full_name, active, created_at, updated_at
FROM personnel
WHERE id = $1
`

func (q *Queries) GetPersonnel(ctx context.Context, id string) (Personnel, error) {
	row := q.db.QueryRow(ctx, getPersonnel, id)
	var i Personnel
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
