// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personnel.sql

package db

import (
	"context"
)

const createPersonnel = `-- name: CreatePersonnel :exec
INSERT INTO personnel (
    id,
    full_name,
    alias,
    rank,
    registration_id,
    section,
    organization_unit
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreatePersonnelParams struct {
	ID               string `json:"id"`
	FullName         string `json:"full_name"`
	Alias            string `json:"alias"`
	Rank             string `json:"rank"`
	RegistrationID   string `json:"registration_id"`
	Section          string `json:"section"`
	OrganizationUnit string `json:"organization_unit"`
}

func (q *Queries) CreatePersonnel(ctx context.Context, arg CreatePersonnelParams) error {
	_, err := q.db.Exec(ctx, createPersonnel,
		arg.ID,
		arg.FullName,
		arg.Alias,
		arg.Rank,
		arg.RegistrationID,
		arg.Section,
		arg.OrganizationUnit,
	)
	return err
}

const getPersonnel = `-- name: GetPersonnel :one
SELECT
    id,
    full_name,
    alias,
    rank,
    registration_id,
    section,
    organization_unit,
    active,
    created_at,
    updated_at
FROM personnel
WHERE id = $1
`

func (q *Queries) GetPersonnel(ctx context.Context, id string) (Personnel, error) {
	row := q.db.QueryRow(ctx, getPersonnel, id)
	var i Personnel
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Alias,
		&i.Rank,
		&i.RegistrationID,
		&i.Section,
		&i.OrganizationUnit,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPersonnel = `-- name: ListPersonnel :many
SELECT
    id,
    full_name,
    alias,
    rank,
    registration_id,
    section,
    organization_unit,
    active,
    created_at,
    updated_at
FROM personnel
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListPersonnel(ctx context.Context, limitCount int32) ([]Personnel, error) {
	rows, err := q.db.Query(ctx, listPersonnel, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Personnel{}
	for rows.Next() {
		var i Personnel
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Alias,
			&i.Rank,
			&i.RegistrationID,
			&i.Section,
			&i.OrganizationUnit,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPersonnel = `-- name: SearchPersonnel :many
SELECT
    id,
    full_name,
    alias,
    rank,
    registration_id,
    section,
    organization_unit,
    active,
    created_at,
    updated_at
FROM personnel
WHERE full_name ILIKE $1::text ESCAPE '\'
   OR alias ILIKE $1::text ESCAPE '\'
   OR registration_id ILIKE $1::text ESCAPE '\'
   OR registration_id ILIKE $2::text ESCAPE '\'
   OR rank ILIKE $1::text ESCAPE '\'
   OR section ILIKE $1::text ESCAPE '\'
   OR organization_unit ILIKE $1::text ESCAPE '\'
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type SearchPersonnelParams struct {
	SearchPattern       string `json:"search_pattern"`
	RegistrationPattern string `json:"registration_pattern"`
	LimitCount          int32  `json:"limit_count"`
}

func (q *Queries) SearchPersonnel(ctx context.Context, arg SearchPersonnelParams) ([]Personnel, error) {
	rows, err := q.db.Query(ctx, searchPersonnel, arg.SearchPattern, arg.RegistrationPattern, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Personnel{}
	for rows.Next() {
		var i Personnel
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Alias,
			&i.Rank,
			&i.RegistrationID,
			&i.Section,
			&i.OrganizationUnit,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
